FoodDefence/Controllers/ORDEN_TRABAJO_CARGAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodDefence.Models;
using FoodDefence.Models.objectModel;
using FoodDefence.Models.Repository;
using FoodDefence.Models.Request;

namespace FoodDefense.Controllers
{
    public class ORDEN_TRABAJO_CARGAController : Controller
    {


        // GET: ORDEN_TRABAJO_CARGA
        public ActionResult Index()
        {
            FoodDefense_DevEntities db = new FoodDefense_DevEntities();
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            cleanSession();
            return View();
        }

        public ActionResult ListadoOrdenesTrabajo(string pCliente = ""
                                                , string pEmpleado = ""
                                                , string pFechaDesde = ""
                                                , string pFechaHasta = ""
                                                )
        {

            DateTime? lFechaDesde = null;
            DateTime? lFechaHasta = null;
            if (pFechaDesde != "")
                lFechaDesde = Convert.ToDateTime(pFechaDesde);
            if (pFechaHasta != "")
                lFechaHasta = Convert.ToDateTime(pFechaHasta);


            FoodDefense_DevEntities db = new FoodDefense_DevEntities();
            List<OrdenesTrabajo_Result> lDatos = db.st_getOrdenesTrabajo(pCliente, pEmpleado, lFechaDesde, lFechaHasta, 2).ToList();

            return PartialView("_ListadoOrdenesTrabajo", lDatos);
        }


        public ActionResult Create(int id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            FoodDefense_DevEntities db = new FoodDefense_DevEntities();

            cleanSession();
            ViewBag.ValidacionesOrdenTrabajo = "";

            ORDEN_TRABAJO oRDEN_TRABAJO = db.ORDEN_TRABAJO.Find(id);
            if (oRDEN_TRABAJO == null)
            {
                return HttpNotFound();
            }

            CLIENTE_LOCACION cLIENTE_LOCACION = db.CLIENTE_LOCACION.Where(w => w.id == oRDEN_TRABAJO.idClienteLocacion).First();
            ViewBag.Cliente = db.CLIENTE.Where(w => w.id == cLIENTE_LOCACION.idCliente).Select(s => s.razonSocial).First();

            EMPLEADO eMPLEADO = db.EMPLEADO.Where(w => w.id == oRDEN_TRABAJO.idEmpleado).First();
            ViewBag.Empleado = eMPLEADO.apellido + ", " + eMPLEADO.nombre;

            return View(oRDEN_TRABAJO);
        }

        public JsonResult ComboTipoTrampa()
        {
            FoodDefense_DevEntities db = new FoodDefense_DevEntities();
            db.Configuration.ProxyCreationEnabled = false;
            List<TRAMPA_TIPO> lista = db.TRAMPA_TIPO.Where(w => w.baja == false).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getTrampas(int idOrdenTrabajo)
        {
            try
            {
                CargaTrabajoRepository oRep = new CargaTrabajoRepository();
                List<TipoTrampas_OrdenTrabajo> lst = oRep.getTrampaGroupTipos(idOrdenTrabajo);
                if (lst.Count > 0)
                {
                    return Json(lst, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("VACIO", JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception e)
            {
                return Json("ERROR", JsonRequestBehavior.AllowGet);
                throw;
            }

        }

        public JsonResult getTrampasById(int id, string pNumeroTrampa, int pTipo)
        {
            try
            {
                CargaTrabajoRepository oRep = new CargaTrabajoRepository();
                Trampas_OrdenTrabajo oTrampa = oRep.getTrampaByNumero(id, pNumeroTrampa, pTipo);


                if (oTrampa != null)
                {

                    return Json(oTrampa, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("VACIO", JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception)
            {
                return Json("ERROR", JsonRequestBehavior.AllowGet);
                throw;
            }

        }


        [HttpGet]
        public ActionResult CargaTrabajo(int id)
        {
            Trampas_OrdenTrabajoDetalle trampas_OrdenTrabajo = new Trampas_OrdenTrabajoDetalle();
            trampas_OrdenTrabajo = armarControl("C",id);
            return PartialView(trampas_OrdenTrabajo);
        }

        [HttpGet]
        public ActionResult VerTrabajo(int id)
        {
            Trampas_OrdenTrabajoDetalle trampas_OrdenTrabajo = new Trampas_OrdenTrabajoDetalle();
            trampas_OrdenTrabajo = armarControl("V", id);
            return PartialView(trampas_OrdenTrabajo);
        }

        public Trampas_OrdenTrabajoDetalle armarControl(string tipoVista, int id) {
            //tipoVista = "C" cargar "V" ver

            Trampas_OrdenTrabajoDetalle trampas_OrdenTrabajo = new Trampas_OrdenTrabajoDetalle();
            CargaTrabajoRepository oRep = new CargaTrabajoRepository();
            trampas_OrdenTrabajo = oRep.getTrampaDetalle(id);
            //activar controles
            List<string> controles = oRep.getCampoRequeridoCargaControlTrampa(trampas_OrdenTrabajo.idTipoTrampa);

            if (tipoVista == "V") {
                //idEstado
                if (controles.Any(s => s.Contains("idEstado")))
                {
                    trampas_OrdenTrabajo.is_idEstado = "S";
                    TRAMPA_CONTROL_ESTADO controlEstado = oRep.getTrampaControlEstadoById((int)trampas_OrdenTrabajo.idEstado);
                    trampas_OrdenTrabajo.descripcionEstado = controlEstado.descripcion + "(" + controlEstado.abreviatura + ")";
                }
                //idAccion
                if (controles.Any(s => s.Contains("idAccion")))
                {
                    trampas_OrdenTrabajo.is_idAccion = "S";
                    TRAMPA_CONTROL_ACCION controlAccion = oRep.getTrampaControlAccionById((int)trampas_OrdenTrabajo.idAccion);
                    trampas_OrdenTrabajo.descripcionAccion = controlAccion.descripcion + "(" + controlAccion.abreviatura + ")";
                }
            }
            if (tipoVista == "C") {
                //idEstado
                if (controles.Any(s => s.Contains("idEstado")))
                {
                    trampas_OrdenTrabajo.is_idEstado = "S";
                    var lst = (from p in oRep.getTrampaControlEstado(trampas_OrdenTrabajo.idTipoTrampa)
                               select new
                               {
                                   p.id,
                                   descripcion = p.descripcion + '(' + p.abreviatura + ')'
                               }
                              ).ToList();

                    trampas_OrdenTrabajo.cmbEstado = new SelectList(lst, "id", "descripcion");
                    FoodDefense_DevEntities db = new FoodDefense_DevEntities();
                    List <int> lstSelect = (from est in db.TRAMPA_CONTROL_ESTADO
                                              join det in db.ORDEN_TRABAJO_DETALLE_ESTADO on est.id equals det.idEstado
                                              where det.idOrdenTrabajoDetalle == id
                                              select est.id).ToList() ;
                    trampas_OrdenTrabajo.listEstado = lstSelect;
                    if (lstSelect.Count() > 0 && trampas_OrdenTrabajo.multiSelTipoTrampa == false)
                    {
                        trampas_OrdenTrabajo.idEstado = lstSelect[0];
                    }                    
                }
                //idAccion
                if (controles.Any(s => s.Contains("idAccion")))
                {
                    trampas_OrdenTrabajo.is_idAccion = "S";
                    var lst = (from p in oRep.getTrampaControlAccion(trampas_OrdenTrabajo.idTipoTrampa)
                               select new
                               {
                                   p.id,
                                   descripcion = p.descripcion + '(' + p.abreviatura + ')'
                               }
                                      ).ToList();
                    trampas_OrdenTrabajo.cmbAccion = new SelectList(lst, "id", "descripcion", trampas_OrdenTrabajo.idAccion);
                }
            }
            //moscas
            if (controles.Any(s => s.Contains("moscas")))
            {
                trampas_OrdenTrabajo.is_moscas = "S";
            }
            //mosquitas
            if (controles.Any(s => s.Contains("mosquitas")))
            {
                trampas_OrdenTrabajo.is_mosquitas = "S";
            }
            //polillas
            if (controles.Any(s => s.Contains("polillas")))
            {
                trampas_OrdenTrabajo.is_polillas = "S";
            }
            //mariposas
            if (controles.Any(s => s.Contains("mariposas")))
            {
                trampas_OrdenTrabajo.is_mariposas = "S";
            }
            //minusculos
            if (controles.Any(s => s.Contains("minusculos")))
            {
                trampas_OrdenTrabajo.is_minusculos = "S";
            }
            //roedor
            if (controles.Any(s => s.Contains("roedor")))
            {
                trampas_OrdenTrabajo.is_roedor = "S";
            }
            //insecto
            if (controles.Any(s => s.Contains("insecto")))
            {

FoodDefence/Views/ORDEN_TRABAJO_CARGA/Details.cshtml
@model FoodDefence.Models.ORDEN_TRABAJO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/ViewsResources/orden_trabajo.css")" rel="stylesheet" type="text/css" />

<div class="callout callout-primary">

    <h4><i class="fa fa-list-alt"></i> Carga de Trabajo</h4>
    <br />


    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formCargaTrabajo" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id, new { @id = "hd_idOrdenTrabajo" })
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-row">
                <div class="form-group col-md-3">
                    <b>Fecha de carga</b>
                    <div>
                        @string.Format("{0:dd/MM/yyyy}", @Model.fechaCargaOrden)
                    </div>
                </div>
                <div class="form-group col-md-3">
                    <b>Fecha de realización de trabajo</b>
                    <div>
                        @string.Format("{0:dd/MM/yyyy}", @Model.fechaDeTrabajo)
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <b>Técnico</b>
                    <div>
                        @ViewBag.Empleado
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <b>Cliente</b>
                    <div>
                        @ViewBag.Cliente
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <b>Locación</b>
                    <div>
                        @Html.DisplayFor(model => model.CLIENTE_LOCACION.descripcion)
                        @Html.HiddenFor(model => model.CLIENTE_LOCACION.id, new { @id = "cmbClienteLocacion" })
                    </div>
                </div>
            </div>
            <hr />
            <div>
                <div class="form-row">
                    <b>Trampas</b>
                </div>
                <div style="display:none" id="waitTrampa" class="form-row">
                    <div class="d-flex align-items-center col-md-4">
                        <strong>Cargando trampas...</strong>
                        <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div>
                    </div>
                </div>
                <div class="form-row">
                    <div id="div_tblDatosTrampas" class="col-md-12">
                        <div id="tblDatosTrampas"></div>
                    </div>
                </div>
            </div>

            <div class="form-group mt-3">
                @if (ViewBag.Finalizar == "S")
                {
                    <button type="button" id="btnFinalizar" data-wait="btn" class="btn btn-outline-success">Finalizar Carga de Trabajo</button>
                }
                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-outline-primary", @id = "btnVolver", @data_wait = "btn" })
            </div>

        </div>
    }

</div>

<button class="btn btn-primary scroll-top" data-scroll="up" type="button">
    <i class="fa fa-chevron-up"></i>
</button>
<!-- Modal Carga Trabajo -->
<div class="modal fade" data-backdrop="static" id="VerTrabajoModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Carga de trabajo</h5>
                <button type="button" class="close" data-dismiss="modal" data-wait="modal-btn" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="VerTrabajoModalBody" class="modal-body">
                Espere por favor......
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap Modal Confirm -->
<div class="modal" tabindex="-1" role="dialog" id="modalConfirm">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="modalConfirmMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" id="modalConfirm-btn-si" class="btn btn-primary">Si</button>
                <button type="button" id="modalConfirm-btn-no" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap Modal -->
<div class="modal fade" id="modalAlert" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">Atención</h4>
            </div>
            <div class="modal-body">
                <p id="modalMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


    $(document).ready(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) {
                $('.scroll-top').fadeIn();
            } else {
                $('.scroll-top').fadeOut();
            }
        });

        $('.scroll-top').click(function () {
            $("html, body").animate({
                scrollTop: 0
            }, 100);
            return false;
        });

         $('[data-toggle="tooltip"]').tooltip()
         cargarTrampas();

    });

    $("#formCargaTrabajo").bind("keypress", function (e) {
        if (e.keyCode == 13) {
        return false;
        }
     });

    function finalizar() {

        var idOrdenTrabajo = $('#hd_idOrdenTrabajo').val();
        $('#btnFinalizar').html('<span class="spinner-border spinner-border-sm mr-2 text-success" role="status" aria-hidden="true"></span>Finalizar Carga de Trabajo');
        $('[data-wait="btn"]').attr("disabled", true).addClass('disabled');
        let dataResponse = { idOrdenTrabajo: idOrdenTrabajo };
        $.ajax({
            url: '@Url.Action("finalizarTrabajo")'
            , type:"POST"
            , dataType: 'json'
            , data: JSON.stringify(dataResponse)
            , contentType: "application/json; charset=utf-8"
            , success: function (data) {
                if (data == 'OK') {
                        window.location.href = '@Url.Action("Index", "ORDEN_TRABAJO_CARGA")'
                }
                else {
                    mostrarMensaje(data);
                    return null;
                }
            }
        });
    }

    $("#btnFinalizar").click(function () {
        $('#modalConfirmMessage').html("¿Desea finalizar el trabajo cargado?");
        $('#modalConfirm-btn-si').off("click");
        $('#modalConfirm-btn-si').on('click', function () {
            $('#modalConfirm').modal('hide');
            finalizar();
        });
        $('#modalConfirm').modal('show');
    });
    
    function cargarTrampas() {
        var idOrdenTrabajo = $('#hd_idOrdenTrabajo').val();
        $('#tblDatosTrampas').remove();
        $('#divXtrampa').hide();

        $.ajax({
            url: '@Url.Action("getTrampas")'
            , type:"GET"
            , dataType: 'json'
            , data: { idOrdenTrabajo: idOrdenTrabajo }
            , beforeSend: function () {
                $('#waitTrampa').show();
            }
            , success: function (data) {
                if (data == "VACIO") {
                    $('#waitTrampa').hide();
                    mostrarMensaje("Error no hay trampas");
                }
                else {
                    if (data == "ERROR") {
                        $('#waitTrampa').hide();
                        mostrarMensaje("Error al cargar trampas");
                    }
                    else {
                        armarTrampas(data);
                        $('#waitTrampa').hide();
                    }
                }
            }
        });
    }

    function armarTrampas(data) {
        if (data.length > 0) {
            $('#div_tblDatosTrampas').append(
                ' <div id="tblDatosTrampas" class="container"> </div>'
                );

            let cab = "";
            for (var i = 0; i < data.length; i++) {
                //DETALLE
                let det = '<ul  class="list-group">';
                for (var e = 0; e < data[i].trampas.length; e++) {
                    let cargado = "";
                    if (data[i].trampas[e].cargado == true) {
                        cargado = '<button  type="button" data-wait="btn" class="btn btn-outline-primary btn-sm" onClick="trampaCargarTrabajo(' + data[i].trampas[e].idOrdenTrabajoDetalle + ')" id="btn_cargar_' + data[i].trampas[e].idOrdenTrabajoDetalle + '"' + '>' +
                            'Ver Trabajo' +
                            '</button>'
                    }
                    else {
                        cargado = '<h5> <span class="badge badge-secondary" > Sin Trabajo Cargado</span ></h5 >';
                    }

                    det = det +
                        '<li style="cursor:pointer" class="list-group-item">' +
                        '<div class="d-flex w-100 justify-content-between">'+
                       '<h6>' + data[i].trampas[e].descripcion + ' <span class="badge badge-primary">' + data[i].trampas[e].numero + '</span></h6>' +
                        cargado +
                        '</div>' +
                            '</li>'
                }

                det = det + '</ul>'

                //CABECERA
                 cab = cab +
                    '<div class="card">' +
                     '<div class="card-header collapsed" href="#cab' + data[i].idTipoTrampa + '" class="" data-toggle="collapse" data-target="#cab' + data[i].idTipoTrampa + '" aria-expanded="false">' +
                        '<span class="title">' + data[i].descTipoTrampa  + '</span>' +
                        '<span class="accicon"><i class="fa fa-chevron-down rotate-icon"></i></span>' +
                     '</div> ' +
                     '<div id="cab' + data[i].idTipoTrampa + '" class="collapse" data-parent="#tblDatosTrampas">' +
                        '<div class="card-body">' + det + '</div>' +
                     '</div>' +
                    '</div>'
            }

            $('#tblDatosTrampas').append(cab);
            $('[data-toggle="tooltip"]').tooltip()
        }
    }


    function trampaCargarTrabajo(idOrdenTrabajoDetalle) {

        $('#btn_cargar_' + idOrdenTrabajoDetalle).html('<span  class="spinner-border spinner-border-sm mr-2 text-primary" role="status" aria-hidden="true"></span>Ver Trabajo');
        $('[data-wait="btn"]').attr("disabled", true);
        $('[data-wait="btn"]').addClass('disabled');

        var url = '@Url.Action("VerTrabajo")' + '/' + idOrdenTrabajoDetalle

        $.get(url, function(data) {
            $('#VerTrabajoModalBody').html(data);
            $('#btn_cargar_' + idOrdenTrabajoDetalle).html('Ver Trabajo')
            $('[data-wait="btn"]').attr("disabled", false);
            $('[data-wait="btn"]').removeClass('disabled');

            $('#VerTrabajoModal').modal('show');
        });
    }

    function mostrarMensaje(mensaje) {
        $("#modalMessage").html(mensaje);
        $('#modalAlert').modal("show");
    }

</script>

FoodDefence/Views/ORDEN_TRABAJO_CARGA/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="callout callout-primary">

    <h4><i class="fa fa-list-alt"></i> Carga de trabajo</h4>
    <br />
        

    <div class="table-responsive-sm">
        <table class="table-sm">
            <tr>
                <td>Cliente</td>
                <td>Técnico</td>                
                <td>Fecha Carga Desde</td>
                <td>Fecha Carga Hasta</td>
                <td></td>
            </tr>
            <tr>
                <td>                    
                    <input type="text"  id="txtCliente"  name="txtCliente" value=""  class = "form-control" />
                </td>
                <td>                    
                    <input type="text" id="txtEmpleado" name="txtEmpleado" value="" class="form-control" />
                </td>
                <td>                    
                    <div style="position: relative">
                        <input type="text" id="txtFechaDesde" name="txtFechaDesde" value="" class="form-control" />
                    </div>
                </td>
                <td>
                    <div style="position: relative">
                        <input type="text" id="txtFechaHasta" name="txtFechaHasta" value="" class="form-control" />
                    </div>                    
                </td>
                <td>
                    <input type="button" id="btnBuscar" class="btn btn-outline-secondary" onclick="btnBuscar_onclic()" value="Buscar" />
                </td>
            </tr>
        </table>
    </div>

    <div id="divTabla">

    </div>

</div>
<script>
    $(document).ready(function () {
        limpiar();
        $(function () {
            $('#txtFechaDesde').datetimepicker({
                format: 'DD/MM/YYYY',
                locale: 'es'
            });
            $('#txtFechaHasta').datetimepicker({
                format: 'DD/MM/YYYY',
                locale: 'es'
            });
        });
    });

    function limpiar() {
        $('#txtCliente').val('');
        $('#txtEmpleado').val('');
        $('#txtFechaDesde').val('');
        $('#txtFechaHasta').val('');

    }

    function btnBuscar_onclic() {
        var lCliente = $('#txtCliente').val();
        var lEmpleado = $('#txtEmpleado').val();
        var lFechaDesde = $('#txtFechaDesde').val();
        var lFechaHasta = $('#txtFechaHasta').val();


        $.ajax({
                url: '@Url.Action("ListadoOrdenesTrabajo", "ORDEN_TRABAJO_CARGA")'
                , data: {
                        pCliente: lCliente
                        , pEmpleado: lEmpleado
                        , pFechaDesde: lFechaDesde
                        , pFechaHasta: lFechaHasta
                        }
            , success: function (data) {
                                        $("#divTabla").html(data);
                                        limpiar();
                                       }
        });
    }
</script>

FoodDefence/Views/ORDEN_TRABAJO_CARGA/_ListadoOrdenesTrabajo.cshtml
@model List<FoodDefence.Models.OrdenesTrabajo_Result>

<div>
    <table class="table table-bordered table-sm">
        <tr class="d-flex">
            <th class="priority-1 col-md-1">
                #
            </th>
            <th class="priority-1 col-md-2">
                Cliente
            </th>
            <th class="priority-1 col-md-2">
                Locación
            </th>
            <th class="priority-2 col-md-2">
                Fecha Carga
            </th>
            <th class="priority-2 col-md-2">
                Fecha Trabajo
            </th>
            <th class="priority-3 col-md-2" data-toggle="tooltip" title="Porcentaje de Trabajo Cargado">
                % Trabajo Cargado
            </th>
            <th class="priority-1 col-md-1"></th>
        </tr>
        @for (int i = 0; i < Model.Count(); i++)        
        {
        <tr class="d-flex">
            <td class="priority-1 col-md-1">
                @Model[i].id
            </td>
            <td class="priority-1 col-md-2">
                @Model[i].cliente
            </td>
            <td class="priority-1 col-md-2">
                @Model[i].locacion
            </td>
            <td class="priority-2 col-md-2">
                @string.Format("{0:dd/MM/yyyy}", @Model[i].fechaCargaOrden)
            </td>
            <td class="priority-3 col-md-2">
                @string.Format("{0:dd/MM/yyyy}", @Model[i].fechaDeTrabajo)
            </td>
            <td class="priority-3 col-md-2">
                <div class="progress" id="progressId_@Model[i].id" data-toggle="tooltip" title="Porcentaje de Trabajo Cargado">
                    <div class="progress-bar" role="progressbar" style="width: @Model[i].porcentaje%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                        @*@Model[i].porcentaje%*@
                    </div>
                    <span class="progress-completed">@Model[i].porcentaje%</span>
                </div>
            </td>
            <td class="priority-1 col-md-1">
                <div class="btn-group btn-group-primary">
                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Aciones
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @Html.ActionLink("Ver", "Details", "ORDEN_TRABAJO_CARGA", new { id = @Model[i].id, finalizar = "N" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Cargar Trabajo", "Create", "ORDEN_TRABAJO_CARGA", new { id = @Model[i].id }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Finalizar", "Details", "ORDEN_TRABAJO_CARGA", new { id = @Model[i].id, finalizar = "S" }, new { @class = "dropdown-item" })
                        
                    </div>
                </div>


            </td>
        </tr>
        }
    </table>
</div>

<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })


    //function cargarProgreso() {
    //    $("#dynamic")
    //        .css("width", current_progress + "%")
    //        .attr("aria-valuenow", current_progress)
    //        .text(current_progress + "% Complete");
    //}
</script>