FoodDefence/Models/CONTROL_PLAGA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_PLAGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTROL_PLAGA()
        {
            this.CONTROL_PLAGA_DETALLE = new HashSet<CONTROL_PLAGA_DETALLE>();
        }
    
        public int id { get; set; }
        public int idClienteLocacion { get; set; }
        public int idTipoTrampa { get; set; }
        public string campoCondicion { get; set; }
        public string operadorCondicion { get; set; }
        public decimal valorCondicion { get; set; }
    
        public virtual CLIENTE_LOCACION CLIENTE_LOCACION { get; set; }
        public virtual TRAMPA_TIPO TRAMPA_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PLAGA_DETALLE> CONTROL_PLAGA_DETALLE { get; set; }
    }
}

FoodDefence/Controllers/CONTROL_PLAGAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodDefence.Models;
using FoodDefence.Models.objectModel;
using FoodDefence.Models.Repository;

namespace FoodDefence.Controllers
{
    public class CONTROL_PLAGAController : Controller
    {
        private FoodDefense_DevEntities db = new FoodDefense_DevEntities();

        // GET: CONTROL_PLAGA
        public ActionResult Index()
        {
            FoodDefense_DevEntities db = new FoodDefense_DevEntities();
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            var cONTROL_PLAGA = db.CONTROL_PLAGA.Include(c => c.CLIENTE_LOCACION).Include(c => c.TRAMPA_TIPO);
            List<CLIENTE> cLIENTES = db.CLIENTE.Where(n => n.baja == false).ToList();
            cLIENTES.Add(new CLIENTE { id = 0, razonSocial = "TODOS" });
            ViewBag.idCliente = new SelectList(cLIENTES.OrderBy(o => o.id), "id", "razonSocial", 0);
            ViewBag.idTrampaTipo = new SelectList(db.TRAMPA_TIPO, "id", "descripcion");

            return View(cONTROL_PLAGA.ToList());
        }

        public ActionResult ListadoControlPlaga(string pCliente = "", string pClienteLocacion = "", int pTipoTrampa = 0, string pCampoCondicion = "")
        {
            List<st_GetListaControlPlaga_Result> listado = db.st_GetListaControlPlaga(pCliente, pClienteLocacion, pTipoTrampa, pCampoCondicion).ToList();
            ViewData["listado"] = listado;
            return PartialView("_ListadoControlPlaga");
        }

        // GET: CONTROL_PLAGA/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CONTROL_PLAGA cONTROL_PLAGA = db.CONTROL_PLAGA.Find(id);
            if (cONTROL_PLAGA == null)
            {
                return HttpNotFound();
            }

            CLIENTE_LOCACION cLIENTE_LOCACION = db.CLIENTE_LOCACION.Find(cONTROL_PLAGA.idClienteLocacion);
            ViewBag.razonSocial = db.CLIENTE.Find(cLIENTE_LOCACION.idCliente).razonSocial;

            List<TAREA> tareasDetalles;
            tareasDetalles = (from tar in db.TAREA
                              join det in db.CONTROL_PLAGA_DETALLE on tar.id equals det.idTarea
                              where det.idControlPlaga == id
                              select tar).ToList();

            ViewBag.tareasDetalles = tareasDetalles.ToList();

            return View(cONTROL_PLAGA);
        }

        // GET: CONTROL_PLAGA/Create
        public ActionResult Create()
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            ViewBag.idCliente = new SelectList(db.CLIENTE.Where(n => n.baja == false), "id", "razonSocial", null);
            ViewBag.idTipoTrampa = new SelectList(db.TRAMPA_TIPO, "id", "descripcion");
            ViewBag.idTarea = new SelectList(db.TAREA.Where(n => n.idTipoTrampa == 1), "id", "descripcion");
            ViewBag.operadorCondicion = new SelectList(obternetOperador(), "id", "descripcion");

            return View();
        }

        // POST: CONTROL_PLAGA/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,idClienteLocacion,idTipoTrampa,campoCondicion,operadorCondicion,valorCondicion")]
                                    CONTROL_PLAGA cONTROL_PLAGA, FormCollection fConllection)
        {
            var idTareas = fConllection["idTarea"];
            var campoCondicion = fConllection["campoCondicion"];

            ViewBag.ValidacionesControlPlaga = "";
            if (string.IsNullOrEmpty(cONTROL_PLAGA.campoCondicion))
            {
                ViewBag.ValidacionesControlPlaga = "Ingrese una Campo Condición.";
            } else
            {
                if (cONTROL_PLAGA.campoCondicion.Trim().Length == 0)
                {
                    ViewBag.ValidacionesControlPlaga = "Ingrese una Campo Condición.";
                }
            }

            if (idTareas == null && ViewBag.ValidacionesControlPlaga == "")
            {
                ViewBag.ValidacionesControlPlaga = "Seleccione una Tarea.";
            }

            if (cONTROL_PLAGA.idClienteLocacion == 0)
            {
                ViewBag.ValidacionesControlPlaga = "Seleccione una Locación.";
            }

            if (ModelState.IsValid && ViewBag.ValidacionesControlPlaga == "")
            {
                db.CONTROL_PLAGA.Add(cONTROL_PLAGA);
                db.SaveChanges();
                var idNew = cONTROL_PLAGA.id;
                string[] tareas = idTareas.Split(',');

                foreach (var t in tareas)
                {
                    CONTROL_PLAGA_DETALLE cONTROL_PLAGA_DETALLE = new CONTROL_PLAGA_DETALLE();
                    cONTROL_PLAGA_DETALLE.idControlPlaga = idNew;
                    cONTROL_PLAGA_DETALLE.idTarea = Int32.Parse(t);
                    db.CONTROL_PLAGA_DETALLE.Add(cONTROL_PLAGA_DETALLE);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            } else
            {
                ViewBag.idCliente = new SelectList(db.CLIENTE.Where(n => n.baja == false), "id", "razonSocial", null);
                ViewBag.idTipoTrampa = new SelectList(db.TRAMPA_TIPO, "id", "descripcion");
                ViewBag.idTarea = new SelectList(db.TAREA.Where(n => n.idTipoTrampa == 1), "id", "descripcion");
                ViewBag.operadorCondicion = new SelectList(obternetOperador(), "id", "descripcion");

                return View(cONTROL_PLAGA);
            }


        }

        // GET: CONTROL_PLAGA/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTROL_PLAGA cONTROL_PLAGA = db.CONTROL_PLAGA.Find(id);
            if (cONTROL_PLAGA == null)
            {
                return HttpNotFound();
            }

            CLIENTE_LOCACION cLIENTE_LOCACION = db.CLIENTE_LOCACION.Find(cONTROL_PLAGA.idClienteLocacion);
            ViewBag.idCliente = new SelectList(db.CLIENTE, "id", "razonSocial", cLIENTE_LOCACION.idCliente);
            ViewBag.idClienteLocacion = new SelectList(db.CLIENTE_LOCACION.Where(n => n.idCliente == cLIENTE_LOCACION.idCliente), "id", "descripcion", cONTROL_PLAGA.idClienteLocacion);

            ViewBag.idTipoTrampa = new SelectList(db.TRAMPA_TIPO, "id", "descripcion", cONTROL_PLAGA.idTipoTrampa);
            ViewBag.idTarea = new SelectList(db.TAREA.Where(n => n.idTipoTrampa == cONTROL_PLAGA.idTipoTrampa), "id", "descripcion");
            ViewBag.idTareaSelect = new SelectList(db.CONTROL_PLAGA_DETALLE.Where(d => d.idControlPlaga == id), "idTarea", "id");
            ViewBag.campoCondicion = new SelectList(ComboCamposControlEdit(cONTROL_PLAGA.idTipoTrampa), "campo", "campo", cONTROL_PLAGA.campoCondicion);
            if (cONTROL_PLAGA.campoCondicion == "Estado")
            {
                CargaTrabajoRepository oRep = new CargaTrabajoRepository();
                var rst = (from p in oRep.getTrampaControlEstado(cONTROL_PLAGA.idTipoTrampa)
                           select new
                           {
                               p.id,
                               descripcion = p.descripcion + '(' + p.abreviatura + ')'
                           }
                       ).ToList();
                ViewBag.operadorCondicion = new SelectList(rst, "id", "descripcion", cONTROL_PLAGA.operadorCondicion);
            } else
            {
                // ViewBag.campoCondicion = new SelectList(ComboCamposControlEdit(cONTROL_PLAGA.idTipoTrampa), "campo", "campo", cONTROL_PLAGA.campoCondicion);
                ViewBag.operadorCondicion = new SelectList(obternetOperador(), "id", "descripcion", cONTROL_PLAGA.operadorCondicion);
            }

            return View(cONTROL_PLAGA);
        }

        // POST: CONTROL_PLAGA/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idClienteLocacion,idTipoTrampa,campoCondicion,operadorCondicion,valorCondicion")] CONTROL_PLAGA cONTROL_PLAGA, FormCollection fConllection)
        {
            var idTareas = fConllection["idTarea"];
            var idCP = cONTROL_PLAGA.id;
            ViewBag.ValidacionesControlPlaga = "";
            if (string.IsNullOrEmpty(cONTROL_PLAGA.campoCondicion))
            {
                ViewBag.ValidacionesControlPlaga = "Ingrese una Campo.";
            }
            else
            {

FoodDefence/Views/CONTROL_PLAGA/Create.cshtml
@model FoodDefence.Models.CONTROL_PLAGA

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

<div class="callout callout-primary">
    <h4><i class="fa fa-map-marker"></i> Nueva Tarea de Control</h4>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-row">
                <div class="form-group col-md-6">
                    Cliente
                    <div>
                        @Html.DropDownList("idCliente", null, "Seleccione un cliente", htmlAttributes: new { @class = "form-control", @id = "cmbCliente" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    Locación
                    <div>
                        @Html.DropDownList("idClienteLocacion", Enumerable.Empty<SelectListItem>(), "Primero seleccione un cliente", htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.idClienteLocacion, "", new { @class = "text-danger" })                       
                    </div>
                </div>
            </div>

            <div class="form-row">               
                <div class="form-group col-md-6">
                    Tipo de Trampa
                    <div>
                        @Html.DropDownList("idTipoTrampa", null, "Seleccione tipo de trampa", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idTipoTrampa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    Campo Condición
                    <div>
                        @Html.DropDownList("campoCondicion", Enumerable.Empty<SelectListItem>(), "Primero seleccione un Tipo Trampa", 
                        htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.campoCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">  
                <div class="form-group col-md-3">
                    <div id="operadorLabel"> Operador </div>                    
                    <div class="col-md-15">
                        @Html.DropDownList("operadorCondicion", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-3" id="idValor">                    
                    Valor
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.valorCondicion, new { htmlAttributes = new { @class = "form-control" } })                        
                        @Html.ValidationMessageFor(model => model.valorCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    Acciones
                    <div id="divIdTarea">
                        @Html.ListBox("idTarea", ViewBag.idTarea as MultiSelectList, htmlAttributes: new { @class = "form-control", @id = "idTarea", required = "required", @data_wait = "modal-control", @style = "display:none" })
                        @Html.ValidationMessageFor(model => model.operadorCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" id="btnGuardar" class="btn btn-outline-success">Guardar</button>
                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-outline-primary ml-2", @id = "btnVolver" })
            </div>

            <div id="validaciones" class="alert alert-danger" role="alert">
                <button class="close" data-dismiss="alert"><span>&times;</span></button>
                @ViewBag.ValidacionesControlPlaga
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    var Ingreso = '@ViewBag.ValidacionesControlPlaga'
    var cboTipoTrampa = document.getElementById("idTipoTrampa");
    cboTipoTrampa.addEventListener("change", actTarea);

    $(document).ready(function () {

        //controles
        if (Ingreso != '') {
            $("#validaciones").show();
        }
        else {
            $("#validaciones").hide();
        }

        actMultiCombo();
        //$("#idTarea").chosen();         
    });

    $('#cmbCliente').change(function () {
        $("#cmbCliente option[value='']").remove();
        cargarComboLocacion();
    });

    $('#idTipoTrampa').change(function () {
        $("#idTipoTrampa option[value='']").remove();
        cargarComboCampoCondicion();
    });

    $('#campoCondicion').change(function () {
        cargarCondicionEstado();
    });

    function actTarea() {
        $.ajax({
                url: '@Url.Action("actTarea", "CONTROL_PLAGA")'
                , data: {
                    pIdTrampaTipo: cboTipoTrampa.value
                }
            , success: function (data) {
                    $("#divIdTarea").html(data);
                    actMultiCombo();
                }
        });
    }

    function actMultiCombo() {
        $("#idTarea").multiselect({
            includeSelectAllOption: true,
            selectAllText: '¡Marcar todo!',
            delimiterText: ' - ',
        });
    }

    function cargarComboLocacion() {
        var lcliente = $('#cmbCliente').val();
        $('#idClienteLocacion').empty();
        $.ajax({
            url: '@Url.Action("ComboClienteLocacion", "CLIENTE_LOCACION_SECTOR")'
            , type:"GET"
            , dataType: 'json'
            , data: {pCliente: lcliente}
            , success: function (data) {
                $('#idClienteLocacion').append("<option value=''>Seleccione una locación</option>");
                $.each(data, function (index, row) {
                    $('#idClienteLocacion').append("<option value='" + row.id + "'>" + row.descripcion + "</option>");
                });
            }
        });
    }

    function cargarComboCampoCondicion() {
        var lTrampaTipo = $('#idTipoTrampa').val();
        $('#campoCondicion').empty();
        $('#operadorCondicion').empty();
        $.ajax({
            url: '@Url.Action("ComboCamposControl", "CONTROL_PLAGA")'
            , type:"GET"
            , dataType: 'json'
            , data: { pTrampaTipo: lTrampaTipo }
            , success: function (data) {
                $('#campoCondicion').append("<option value=''>Seleccione una campo Condición</option>");
                $.each(data, function (index, row) {
                    $('#campoCondicion').append("<option value='" + row.campo + "'>" + row.campo + "</option>");
                });
            }
        });
    }

    function cargarCondicionEstado() {
        var opeCondicion = $('#campoCondicion').val();
        var tipo = 0; /*0=Operador, 1=Estado */
        if (opeCondicion == "") { return }
        
        $('#operadorCondicion').empty();
        $('#valorCondicion').val('0');
        if (opeCondicion == "Estado") {
            tipo = $('#idTipoTrampa').val();
            $('#idValor').hide();
            $('#operadorLabel').html("Estado");
        } else {
            tipo = 0;
            $('#operadorLabel').html("Operador");
            $('#idValor').show();
        }        
        
        $.ajax({
            url: '@Url.Action("cargarCondicionEstado", "CONTROL_PLAGA")'
            , type:"GET"
            , dataType: 'json'
            , data: { pTipo: tipo }
            , success: function (data) {                
                console.log("Data: ", tipo);
                if (tipo == 0) {
                    $('#operadorCondicion').append("<option value=''>Seleccione una Condición</option>");                    
                } else {
                    $('#operadorCondicion').append("<option value=''>Seleccione un Estado</option>");                    
                }                
                $.each(data, function (index, row) {
                    
                    $('#operadorCondicion').append("<option value='" + row.id + "'>" + row.descripcion + "</option>");
                });
            }
        });
    }

</script>

FoodDefence/Views/CONTROL_PLAGA/Edit.cshtml
@model FoodDefence.Models.CONTROL_PLAGA

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

<div class="callout callout-primary">
    <h4><i class="fa fa-id-card"></i> Editar Tarea</h4>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-row">
                <div class="form-group col-md-6">
                    Cliente
                    <div>
                        @Html.DropDownList("idCliente", null, "Seleccione un cliente", htmlAttributes: new { @class = "form-control", @id = "cmbCliente" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    Locación
                    <div>
                        @Html.DropDownList("idClienteLocacion", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.idClienteLocacion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">     
                <div class="form-group col-md-6">
                    Tipo Trampa
                    <div>
                        @Html.DropDownList("idTipoTrampa", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idTipoTrampa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    Campo Condición
                    <div>
                        @Html.DropDownList("campoCondicion", null, "Seleccione un Campo", htmlAttributes: new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.campoCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-row">  
                <div class="form-group col-md-3">
                    <div id="operadorLabel"> 
                        @if(@Model.campoCondicion == "Estado")
                        {       @("Estado");  }
                        else {  @("Operador");}
                        
                    </div>
                    <div class="col-md-15">
                        @Html.DropDownList("operadorCondicion", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-3" id="idValor">
                    Valor
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.valorCondicion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.valorCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
 
                <div class="form-group col-md-6">
                    Tareas
                    <div id="divIdTarea">
                        @Html.ListBox("idTarea", ViewBag.idTarea as MultiSelectList, htmlAttributes: new { @class = "form-control", @id = "idTarea", required = "required", @data_wait = "modal-control", @style = "display:none" })
                        @Html.ValidationMessageFor(model => model.operadorCondicion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

             <div class="form-group">
                <button type="submit" id="btnGuardar" class="btn btn-outline-success">Guardar</button>
                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-outline-primary ml-2", @id = "btnVolver" })
            </div>
            <div id="validaciones" class="alert alert-danger" role="alert">
                <button class="close" data-dismiss="alert"><span>&times;</span></button>
                @ViewBag.ValidacionesControlPlaga
            </div>
        </div>
    }
</div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    var Ingreso = '@ViewBag.ValidacionesControlPlaga'
    var cboTipoTrampa = document.getElementById("idTipoTrampa");
    var arrayIdTareaSelect = @Html.Raw(Json.Encode(@ViewBag.idTareaSelect));

    cboTipoTrampa.addEventListener("change", actTarea);
    selTareas();

    $(document).ready(function () {

        //controles
        if (Ingreso != '') {
            $("#validaciones").show();
        }
        else {
            $("#validaciones").hide();
        }

        $("#idTarea").multiselect({ includeSelectAllOption: true });
        //$("#idTarea").chosen();
        var opeCondicion = $('#campoCondicion').val();
        if (opeCondicion == "Estado") {
            $('#idValor').hide();
            $('#operadorLabel').html("Estado");
        } else {
            $('#operadorLabel').html("Operador");
            $('#idValor').show();
        }      

    });

    $('#cmbCliente').change(function () {
        $("#cmbCliente option[value='']").remove();
        cargarComboLocacion();
    });

    $('#idTipoTrampa').change(function () {
        $("#idTipoTrampa option[value='']").remove();
        cargarComboCampoCondicion();
    });

    $('#campoCondicion').change(function () {
        cargarCondicionEstado();
    });

    function actTarea() {
        $.ajax({
                url: '@Url.Action("actTarea", "CONTROL_PLAGA")'
                , data: {
                    pIdTrampaTipo: cboTipoTrampa.value
                }
            , success: function (data) {
                    $("#divIdTarea").html(data);
                    actMultiCombo();
                }
        });
    }

    function actMultiCombo() {
        $("#idTarea").multiselect({
            includeSelectAllOption: true,
            selectAllText: '¡Marcar todo!',
            delimiterText: ' - ',
        });
        selTareas();
    }

    function selTareas() {
        var cbo = document.getElementById('idTarea');
        for (var i = 0; i < arrayIdTareaSelect.length; i++) {
            for (var z = 0; z < cbo.length; z++) {
                // console.log('cbo: ' + cbo[z].value + ' - arrayIdTareaSelect: ' + arrayIdTareaSelect[i].Value);
                if (cbo[z].value == arrayIdTareaSelect[i].Value) {
                    cbo[z].selected = true;
                }
            }
        }
    }


    function cargarComboLocacion() {
        var lcliente = $('#cmbCliente').val();
        $.ajax({
            url: '@Url.Action("ComboClienteLocacion", "CLIENTE_LOCACION_SECTOR")'
            , type:"GET"
            , dataType: 'json'
            , data: {pCliente: lcliente}
            , success: function (data) {
                $('#idClienteLocacion').empty();
                $('#idClienteLocacion').append("<option value=''>Seleccione una locación</option>");
                $.each(data, function (index, row) {
                    $('#idClienteLocacion').append("<option value='" + row.id + "'>" + row.descripcion + "</option>");
                });
            }
        });
    }

    function cargarComboCampoCondicion() {
        var lTrampaTipo = $('#idTipoTrampa').val();
        $.ajax({
            url: '@Url.Action("ComboCamposControl", "CONTROL_PLAGA")'
            , type:"GET"
            , dataType: 'json'
            , data: { pTrampaTipo: lTrampaTipo }
            , success: function (data) {
                $('#campoCondicion').empty();
                $('#campoCondicion').append("<option value=''>Seleccione una campo Condición</option>");
                $.each(data, function (index, row) {
                    $('#campoCondicion').append("<option value='" + row.campo + "'>" + row.campo + "</option>");
                });
            }
        });
    }

    function cargarCondicionEstado() {
        var opeCondicion = $('#campoCondicion').val();
        var tipo = 0; /*0=Operador, 1=Estado */

        console.log("cargarCondicionEstado");
        if (opeCondicion == "") { return }
        $('#operadorCondicion').empty();
        $('#valorCondicion').val('0');
        
        if (opeCondicion == "Estado") {
            tipo = $('#idTipoTrampa').val();
            $('#idValor').hide();
            $('#operadorLabel').html("Estado");
        } else {
            tipo = 0;
            $('#operadorLabel').html("Operador");
            $('#idValor').show();
        }

        $.ajax({
            url: '@Url.Action("cargarCondicionEstado", "CONTROL_PLAGA")'
            , type:"GET"
            , dataType: 'json'
            , data: { pTipo: tipo }
            , success: function (data) {
                console.log("Data: ", tipo);
                if (tipo == 0) {
                    $('#operadorCondicion').append("<option value=''>Seleccione una Condición</option>");
                } else {
                    $('#operadorCondicion').append("<option value=''>Seleccione un Estado</option>");
                }
                $.each(data, function (index, row) {

                    $('#operadorCondicion').append("<option value='" + row.id + "'>" + row.descripcion + "</option>");
                });
            }
        });
    }

</script>

FoodDefence/Views/CONTROL_PLAGA/_ActTarea.cshtml
@Html.ListBox("idTarea", ViewBag.idTarea as MultiSelectList, htmlAttributes: new { @class = "form-control", @id = "idTarea", required = "required", @data_wait = "modal-control", @style = "display:none" })