FoodDefence/Models/TRAMPA_TIPO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDefence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMPA_TIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAMPA_TIPO()
        {
            this.CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA = new HashSet<CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA>();
            this.TRAMPA = new HashSet<TRAMPA>();
            this.TRAMPA_CONTROL_ACCION = new HashSet<TRAMPA_CONTROL_ACCION>();
            this.TRAMPA_CONTROL_ESTADO = new HashSet<TRAMPA_CONTROL_ESTADO>();
            this.GRAFICOS = new HashSet<GRAFICOS>();
            this.TAREA = new HashSet<TAREA>();
            this.CONTROL_PLAGA = new HashSet<CONTROL_PLAGA>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public bool baja { get; set; }
        public Nullable<bool> multiSel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA> CAMPO_REQUERIDO_CARGA_CONTROL_TRAMPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA> TRAMPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA_CONTROL_ACCION> TRAMPA_CONTROL_ACCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAMPA_CONTROL_ESTADO> TRAMPA_CONTROL_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRAFICOS> GRAFICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PLAGA> CONTROL_PLAGA { get; set; }
    }
}

FoodDefence/Controllers/TRAMPA_TIPOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodDefence.Models;

namespace FoodDefense.Controllers
{
    public class TRAMPA_TIPOController : Controller
    {
        private FoodDefense_DevEntities db = new FoodDefense_DevEntities();

        // GET: TRAMPA_TIPO
        public ActionResult Index()
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            return View(db.TRAMPA_TIPO.Where(n=>n.baja==false).ToList());
        }

        // GET: TRAMPA_TIPO/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TRAMPA_TIPO tRAMPA_TIPO = db.TRAMPA_TIPO.Find(id);
            if (tRAMPA_TIPO == null)
            {
                return HttpNotFound();
            }
            return View(tRAMPA_TIPO);
        }

        // GET: TRAMPA_TIPO/Create
        public ActionResult Create()
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            return View();
        }

        // POST: TRAMPA_TIPO/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,descripcion")] TRAMPA_TIPO tRAMPA_TIPO)
        {
            if (ModelState.IsValid)
            {
                tRAMPA_TIPO.baja = false;
                db.TRAMPA_TIPO.Add(tRAMPA_TIPO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tRAMPA_TIPO);
        }

        // GET: TRAMPA_TIPO/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TRAMPA_TIPO tRAMPA_TIPO = db.TRAMPA_TIPO.Find(id);
            if (tRAMPA_TIPO == null)
            {
                return HttpNotFound();
            }
            return View(tRAMPA_TIPO);
        }

        // POST: TRAMPA_TIPO/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,descripcion")] TRAMPA_TIPO tRAMPA_TIPO)
        {
            if (ModelState.IsValid)
            {
                tRAMPA_TIPO.baja = tRAMPA_TIPO.baja;
                db.Entry(tRAMPA_TIPO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tRAMPA_TIPO);
        }

        // GET: TRAMPA_TIPO/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["idUsuario"] == null)
                return RedirectToAction("Ingreso", "Ingresar");
            if (Convert.ToInt32(Session["idUsuario"]) == 0)
                return RedirectToAction("Ingreso", "Ingresar");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TRAMPA_TIPO tRAMPA_TIPO = db.TRAMPA_TIPO.Find(id);
            if (tRAMPA_TIPO == null)
            {
                return HttpNotFound();
            }
            
            return View(tRAMPA_TIPO);
        }

        // POST: TRAMPA_TIPO/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TRAMPA_TIPO tRAMPA_TIPO = db.TRAMPA_TIPO.Find(id);
            if (tRAMPA_TIPO.TRAMPA.Count == 0)
            {
                tRAMPA_TIPO.baja = true;
                db.Entry(tRAMPA_TIPO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(tRAMPA_TIPO);
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FoodDefence/Views/TRAMPA_TIPO/Create.cshtml
@model FoodDefence.Models.TRAMPA_TIPO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TRAMPA_TIPO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FoodDefence/Views/TRAMPA_TIPO/Delete.cshtml
@model FoodDefence.Models.TRAMPA_TIPO

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="callout callout-primary">

    <h4><i class="fa fa-trash"></i> ¿Esta seguro de eliminar este tipo de trampa?</h4>
    <hr />



    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Descripción
            </dt>
            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>
        </dl>

        @if (Model.TRAMPA.Where(n => n.idTrampaEstado == 1).ToList().Count > 0)
        {
            <div class="alert alert-danger" role="alert">
                No se puede dar de baja el tipo de trampa ya que tiene trampas en estado activo asociadass.
            </div>
        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h2>&emsp;</h2>
            <div class="form-actions no-color">
                @if (Model.TRAMPA.Where(n => n.idTrampaEstado == 1).ToList().Count == 0)
                {
                    <input type="submit" value="Eliminar" class="btn btn-outline-danger" />
                }
                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-outline-primary" })
            </div>
        }
    </div>

</div>

FoodDefence/Views/TRAMPA_TIPO/Edit.cshtml
@model FoodDefence.Models.TRAMPA_TIPO

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="callout callout-primary">

    <h4><i class="fa fa-bug"></i> Edición de Tipo de Trampa</h4>
    <br />



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                Descripción
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-success" /> |

                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-outline-primary" })
            </div>
        </div>
    }

    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FoodDefence/Views/TRAMPA_TIPO/Index.cshtml
@model IEnumerable<FoodDefence.Models.TRAMPA_TIPO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="callout callout-primary">
    <h4><i class="fa fa-bug"></i> Tipos de Trampa</h4>
    <br />

    <div>
        <table class="table table-bordered table-sm">
            <tr>
                <th>
                    Descripción
                </th>
                <th>
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "TRAMPA_TIPO", new { id = item.id }, new { @class = "btn btn-outline-dark" })
                        @Html.ActionLink("Eliminar", "Delete", "TRAMPA_TIPO", new { id = item.id }, new { @class = "btn btn-outline-danger" })
                    </td>
                </tr>
            }
        </table>
    </div>

</div>